### ISSUE TITLE
Port to .Net Framework

### ISSUE THREAD

**Issue by snerpton** [mattosaurus/MetOfficeDataPoint#1]
Hi Matt,

Great library. I'm after a Met Office DataPoint library for .Net Framework. I've been unable to find one, and so was going to start from scratch when I stumbled on your .Net Core one. Have you any plans to port it to .Net Framework, or would you mind if I did?

Thanks,
Chris

**Comment by mattosaurus** [comment]
Hi Chris,

I'm happy to port this myself though I won't have a chance to do it before Tuesday (29th) next week. If that works for you then let me know which version you're targeting and I'll add that in, if not then feel free to do it yourself.

Thanks

Matt

**Comment by mattosaurus** [comment]
I managed to get time today so have updated this to work with .NET Framework 4.6.1 as well as .NET Core, this has been published as v2.0 package. Let me know if you experience any issues.

**Comment by snerpton** [comment]
Hi Matt – I've just downloaded the NuGet package and incorporated it into the project I'm working on. It worked perfectly!

Thanks for your effort.
