### ISSUE TITLE
Why the use of LoggerFactory?

### ISSUE THREAD

**Issue by p10tyr** [mattosaurus/MetOfficeDataPoint#2]
https://github.com/mattosaurus/MetOfficeDataPoint/blob/1c61de136beb256866c5e9851be2ce719f4a39c3/MetOfficeDataPoint/Services/MetOfficeDataPointService.cs#L18C65-L18C94

Just curios why the use of Logger Factory in your code. Probably something from early netcore 1 days?
The standard way of using this now a days is simply inject the logger as DI

`ILogger<MetOfficeDataPointService> logger` 

Which registers the class that is then picked up by the factory as needed.

**Comment by mattosaurus** [comment]
Hi,

I believe it's using ILoggerFactory because I normally use Serilog for logging and the extension I was using for it was having issues injecting ILogger at the time (though I could be mistaken). Arguably this doesn't really need a logger injected at all and I could probably just remove it.

**Comment by mattosaurus** [comment]
I've created and published a v3.1.0 release which has a constructor that takes a logger in addition to the one that takes a loggerfactory.
